version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:16.13.2
    steps:
      - checkout
      - run:
          name: install-packages
          command: yarn install
      - run:
          name: test
          command: yarn test